MODEL:
  META_ARCHITECTURE: "ContextRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "ContextRes5ROIHeads"
  CONTEXT:
    NUM_CONTEXT_ITEMS: 8500
    D1: 2048
    D2: 2048
    SOFTMAX_TEMP: 0.01
    NUM_INPUT_FEATS: 1024
    NUM_CONTEXT_FEATS: 2057 # includes bbox location encoding & datetime
    BANKS_DIR: './banks'
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2
VERSION: 2
